import type { Metadata } from "next";
import { Inter, Red_Hat_Text } from "next/font/google";
import "./globals.scss";

const inter = Red_Hat_Text({ subsets: ["latin"] , weight: ["400", "600", "700"] });

export const metadata: Metadata = {
  title: "Product List with Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
